### ISSUE TITLE
关于模型精度

### ISSUE THREAD

**Issue by lambdald** [aoru45/FSANet.Pytorch#1]
你好，请问这个模型你用300W数据训练过吗？用BIWI做测试的话，精度有多少呀？

**Comment by aoru45** [comment]
是的我在300W-LP数据集下训练了，在AFLW2000和BIWI下测试了，BIWI下
-pitch: 5.11 -yaw: 4.53 -roll: 3.89 -mae: 4.51
每帧图片最⻓用时: 58.09 ms 最短用时: 6.44 ms 平均用时: 8.81 ms
